# Site settings
title: Bayern
client:
  name: Client Name
  link: "#client-name"
core-se-link: https://www.secretescapes.de/aktuelle-angebote
se-tracking-link: "?utm_source=SE&utm_medium=hub&utm_campaign=bayern_DE_2019"
description: >
  Ein Urlaub in Bayern lohnt sich auch im Herbst, denn das Wetter ist Ihnen meist noch wohlgesonnen und ermöglicht Wander- und Radtouren, Freizeitaktivitäten im Wald und auf dem Wasser, Stadtbummel in mittelalterlichen Kulissen sowie Biergartenbesuche und Weinproben in der einzigartigen Szenerie des Freistaates.

# file paths
url:     "http://mp.secretescapes.com" # the base hostname & protocol for your site
baseurl: "/de/bayern-herbst" # the subpath of your site, e.g. /blog/
img:     "/de/bayern-herbst/_assets/img"
css:     "/de/bayern-herbst/_assets/css"
js:      "/de/bayern-herbst/_assets/js"


# Build settings
markdown: kramdown
exclude: [node_modules, gulpfile.js, package.json, package-lock.json, js/script.js]
keep_files: [_assets]
sass:
    sass_dir: css
    style: compressed
